# Generated by Django 5.2.17 on 2026-10-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('professor', models.CharField(max_length=150)),
                ('periodo', models.CharField(max_length=10)),
            ],
        ),
    ]
